#!/bin/sh
expected_name="Andrey"
expected_email="andreylikhatin@gmail.com"

name=$(git config --get user.name)
email=$(git config --get user.email)

if [ "$name" != "$expected_name" ] || [ "$email" != "$expected_email" ]; then
  echo "ERROR: git identity must be Andrey <andreylikhatin@gmail.com>" >&2
  echo "Current: $name <$email>" >&2
  exit 1
fi

exit 0
